
create table if not exists public.vsm_projects (
    id bigint generated by default as identity primary key,
    name text not null,
    responsible text,
    date date default current_date,
    status text default 'current' check (status in ('current', 'future', 'completed')),
    lead_time text,
    process_time text,
    efficiency text,
    image_url text,
    miro_link text,
    description text,
    company_id uuid references public.companies(id) on delete cascade,
    takt_time text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.vsm_projects enable row level security;

create policy "Users can view VSM projects from their company"
    on public.vsm_projects for select
    using (
        company_id in (
            select company_id from public.profiles where id = auth.uid()
        )
        OR
        auth.uid() in (
            select id from public.profiles where role = 'superadmin'
        )
    );

create policy "Users can insert VSM projects for their company"
    on public.vsm_projects for insert
    with check (
        company_id in (
            select company_id from public.profiles where id = auth.uid()
        )
        OR
        auth.uid() in (
            select id from public.profiles where role = 'superadmin'
        )
    );

create policy "Users can update VSM projects from their company"
    on public.vsm_projects for update
    using (
        company_id in (
            select company_id from public.profiles where id = auth.uid()
        )
        OR
        auth.uid() in (
            select id from public.profiles where role = 'superadmin'
        )
    );

create policy "Users can delete VSM projects from their company"
    on public.vsm_projects for delete
    using (
        company_id in (
            select company_id from public.profiles where id = auth.uid()
        )
        OR
        auth.uid() in (
            select id from public.profiles where role = 'superadmin'
        )
    );

-- Create bucket for VSM images if it doesn't exist (optimistic approach, might fail if exists but that's ok to ignore distinct failure for bucket creation usually, or check manually first. For simplicity in SQL script often better to do separated or just assume/create if not exists logic which is harder for storage.buckets)
-- We will rely on the app logic or standard storage policies. Usually 'images' bucket exists.
-- Let's ensure a policy exists for the 'images' bucket just in case, or 'vsm-images'
-- Following the existing pattern, probably using 'images' bucket.
